### ISSUE TITLE
Question: .Net and Generics

### ISSUE THREAD

**Issue by The-Futurist** [WildernessLabs/Netduino_SDK#24]
If your system sits on top of the old .Net MF then I assume that generics are not supported?

Can you please summarize what CLR features are not supported and what C# language version is supported?

Do you include any Visual Stduio 2019 project templates?

Is debugging supported?

Thx

**Comment by NevynUK** [comment]
> If your system sits on top of the old .Net MF then I assume that generics are not supported?

Correct.

> Can you please summarize what CLR features are not supported and what C# language version is supported?

You are looking at older versions of C#, think back to VS2013 days.

> Do you include any Visual Stduio 2019 project templates?

VS2019 is not supported.  You can get VS2015 and VS2017 working but these are not explicitly supported.  See the [Netduino Community](https://community.wildernesslabs.co/) for more information.

> Is debugging supported?

Yes for VS2013 and I have had it working for VS2015.
